spring:
  profiles:
    include: local, jwt, apikey, oauth

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 800MB

logging.level:
  shop.matddang: debug

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

etc:
  base-url: ${BASE_URL}
  front-url: ${FRONT_URL}
  front-auth-success: ${FRONT_URL}/auth/success
  google-profile-url: https://www.googleapis.com/userinfo/v2/me
  kakao-profile-url: https://kapi.kakao.com/v2/user/me
  kakao-token-url: https://kauth.kakao.com/oauth/token
  kakao:
    client-id: ${KAKAO_CLIENT}
    redirect-uri: ${BASE_URL}/auth/v1/login/kakao

jwt:
  expiration:
    access: ${ACCESS_EXPIRATION:1_800_000} # 30분
    refresh: ${REFRESH_EXPIRATION:2_592_000_000} # 30일
  secret: ${JWT_SECRET:test-secret-key}

external:
  api:
    vworld:
      url: https://api.vworld.kr/req/address
      key: ${GEO_API_KEY}
